
CC = gcc
CFLAGS = -Wall
PTHREAD = -pthread
LM = -lm

fibonacci: 2-fibonacci.c
	$(CC) $(CFLAGS) -o fibonacci 2-fibonacci.c $(PTHREAD)

pi: 3-pi_thread.c
	$(CC) $(CFLAGS) -o pi 3-pi_thread.c $(PTHREAD) $(LM)
